# Generated by Django 3.1.5 on 2021-01-31 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default='', max_length=80, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='host_name',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=11, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.room')),
            ],
        ),
    ]
